In [1]:
from pymongo import MongoClient
import pandas   as pd 
pd.set_option('display.max_columns', None)  

client = MongoClient('mongodb+srv://user-silvio:1989@cluster-aula.glssz5i.mongodb.net/')
db = client['Aula']
colletion= db.get_collection('anac')

filter={'$and':[{'UF':'MG'},{'Classificacao_da_Ocorrência':'Acidente'}]}
columns ={'Numero_da_Ocorrencia':1,'Classificacao_da_Ocorrência':1,'UF':1,'PSSO':1}

data = list(colletion.find(filter,columns))
df = pd.DataFrame(data)
df.head(5)

,_id,Numero_da_Ocorrencia,Classificacao_da_Ocorrência,UF,PSSO
0,68361c9965b7b847299d068b,7759,Acidente,MG,verdadeiro
1,68361c9965b7b847299d06a2,7516,Acidente,MG,falso
2,68361c9965b7b847299d06ab,7511,Acidente,MG,verdadeiro
3,68361c9965b7b847299d0713,7208,Acidente,MG,verdadeiro
4,68361c9965b7b847299d0773,7703,Acidente,MG,verdadeiro

In [2]:
from pymongo import MongoClient
import pandas   as pd 
pd.set_option('display.max_columns', None)  

client = MongoClient('mongodb+srv://user-silvio:1989@cluster-aula.glssz5i.mongodb.net/')
db = client['Aula']
colletion= db.get_collection('anac')

filter={'$or':[{'UF':'GO'},{'PSSO':'verdadeiro'}]}
columns ={'Numero_da_Ocorrencia':1,'Classificacao_da_Ocorrência':1,'UF':1,'PSSO':1}

data = list(colletion.find(filter,columns))
df = pd.DataFrame(data)
df.head(35)

,_id,Numero_da_Ocorrencia,Classificacao_da_Ocorrência,UF,PSSO
0,68361c9965b7b847299d068a,7762,Incidente,SP,verdadeiro
1,68361c9965b7b847299d068b,7759,Acidente,MG,verdadeiro
2,68361c9965b7b847299d068c,7758,Acidente,GO,verdadeiro
3,68361c9965b7b847299d068d,7758,Acidente,GO,verdadeiro
4,68361c9965b7b847299d068e,7757,Incidente Grave,RS,verdadeiro
5,68361c9965b7b847299d0690,5118,Acidente,ES,verdadeiro
6,68361c9965b7b847299d0693,7754,Incidente Grave,SP,verdadeiro
7,68361c9965b7b847299d0694,7754,Incidente Grave,SP,verdadeiro
8,68361c9965b7b847299d0695,7753,Acidente,SP,verdadeiro
9,68361c9965b7b847299d0697,5665,Acidente,Indeterminado,verdadeiro
10,68361c9965b7b847299d0699,7526,Incidente,MG,verdadeiro
11,68361c9965b7b847299d069b,7524,Ocorrência de Solo,RJ,verdadeiro
12,68361c9965b7b847299d069c,7523,Incidente,SP,verdadeiro
13,68361c9965b7b847299d069d,7522,Acidente,RR,verdadeiro
14,68361c9965b7b847299d069f,7520,Incidente,SP,verdadeiro
15,68361c9965b7b847299d06a0,7519,Incidente,PR,verdadeiro
16,68361c9965b7b847299d06a1,7518,Incidente,PR,verdadeiro
17,68361c9965b7b847299d06a3,7514,Incidente,SC,verdadeiro
18,68361c9965b7b847299d06a4,7517,Incidente,PE,verdadeiro
19,68361c9965b7b847299d06a5,7515,Incidente Grave,MT,verdadeiro
20,68361c9965b7b847299d06a6,7229,Incidente,RJ,verdadeiro
21,68361c9965b7b847299d06a7,7228,Incidente,SP,verdadeiro
22,68361c9965b7b847299d06a8,7227,Ocorrência de Solo,RJ,verdadeiro
23,68361c9965b7b847299d06a9,7513,Incidente,PR,verdadeiro
24,68361c9965b7b847299d06ab,7511,Acidente,MG,verdadeiro
25,68361c9965b7b847299d06ac,7510,Incidente,MG,verdadeiro
26,68361c9965b7b847299d06ad,7236,Incidente,MG,verdadeiro
27,68361c9965b7b847299d06af,7234,Incidente,BA,verdadeiro
28,68361c9965b7b847299d06b0,7233,Acidente,MS,verdadeiro
29,68361c9965b7b847299d06b1,7232,Acidente,AM,verdadeiro
30,68361c9965b7b847299d06b2,7231,Incidente,SC,verdadeiro
31,68361c9965b7b847299d06b3,7230,Incidente,ES,verdadeiro
32,68361c9965b7b847299d06b4,7226,Incidente,MG,verdadeiro
33,68361c9965b7b847299d06b5,7225,Acidente,GO,falso
34,68361c9965b7b847299d06b6,7224,Acidente,SP,verdadeiro