Projeto inserindo dados Json da Anac em banco postgree

Passos do projeto:

1°: importar json como DF 

2°: Tratar os dados levar apenas colunas ["Numero_da_Ocorrencia", "Classificacao_da_Ocorrência", "Data_da_Ocorrencia","Municipio","UF","Regiao","Nome_do_Fabricante"]

3°: Tirar acento de nomes de colunas

4°: Criar Banco de Dados e Tabela 

5°: Configurar a conexão 

6°: Enviar dados para o Postgree

7°: Criar um Delete da tabela para nao ter histórico , mantendo em banco sempre os dados mais rescentes 

8°: Refaturar código (apagar o que nao vai usar)

9°: Nas Aulas estamos treinando com arquivo script estensão Ipynb (notebook)  vamos salvar como extensão PY

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
caminho_do_arquivo = r"C:\Users\silvio\Downloads\Curso BD\Arquivos\01.+Postgree\01. Postgree\Origem de dados\V_OCORRENCIA_AMPLA.json"
df = pd.read_json(caminho_do_arquivo, encoding='utf-8-sig')
df.head(3)

,Numero_da_Ocorrencia,Numero_da_Ficha,Operador_Padronizado,Classificacao_da_Ocorrência,Data_da_Ocorrencia,Hora_da_Ocorrência,Municipio,UF,Regiao,Descricao_do_Tipo,ICAO,Latitude,Longitude,Tipo_de_Aerodromo,Historico,Matricula,Categoria_da_Aeronave,Operador,Tipo_de_Ocorrencia,Fase_da_Operacao,Operacao,Danos_a_Aeronave,Aerodromo_de_Destino,Aerodromo_de_Origem,Lesoes_Fatais_Tripulantes,Lesoes_Fatais_Passageiros,Lesoes_Fatais_Terceiros,Lesoes_Graves_Tripulantes,Lesoes_Graves_Passageiros,Lesoes_Graves_Terceiros,Lesoes_Leves_Tripulantes,Lesoes_Leves_Passageiros,Lesoes_Leves_Terceiros,Ilesos_Tripulantes,Ilesos_Passageiros,Lesoes_Desconhecidas_Tripulantes,Lesoes_Desconhecidas_Passageiros,Lesoes_Desconhecidas_Terceiros,Modelo,CLS,Tipo_ICAO,PMD,Numero_de_Assentos,Nome_do_Fabricante,PSSO
0,7762,201803231711488,ICON TAXI AEREO LTDA E OUTRO,Incidente,2018-03-21,20:00:00,SÃO PAULO,SP,Sudeste,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,None,"-23,6261","-46,6564",None,DURANTE O VOO O PILOTO SENTIU A AERONAVE COM P...,PRROS,TPX,ICON TAXI AEREO LTDA E OUTRO,SCF-NP,Pouso,Táxi Aéreo,Nenhum,SBSP,SDSC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,AW109SP,H2T,A109,3175.0,8.0,AGUSTA,verdadeiro
1,7759,201803161337187,EJ ESCOLA DE AERONAUTICA CIVIL LTDA,Acidente,2018-03-14,15:30:00,MONTES CLAROS,MG,Sudeste,COMBUSTÍVEL,Fora de Aeródromo,"-16,7861","-43,8817",-,QUANDO A AERONAVE ATINGIU 6 MILHAS AO SUL DO A...,PREJO,PRI,EJ ESCOLA DE AERONAUTICA LTDA,FUEL,Em rota,Voo de Instrução,Substancial,SBMK,SIMK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,A152,L1P,C152,757.0,2.0,CESSNA AIRCRAFT,verdadeiro
2,7758,201802271904132,AEROTEX AVIACAO AGRICOLA LTDA.,Acidente,2018-01-26,12:20:00,INACIOLÂNDIA,GO,Centro-Oeste,EXCURSÃO DE PISTA,None,"-18,4572","-49,9842",None,A AERONAVE DECOLAVA DE UMA PISTA DE POUSO EVEN...,PTWZP,S11,AEROTEX AVIAÇÃO AGRÍCOLA LTDA.,RE,Decolagem,Operação Agrícola,Substancial,None,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,T188C,L1P,C188,1997.0,1.0,CESSNA AIRCRAFT,verdadeiro

In [2]:
df.columns

Index(['Numero_da_Ocorrencia', 'Numero_da_Ficha', 'Operador_Padronizado',
       'Classificacao_da_Ocorrência', 'Data_da_Ocorrencia',
       'Hora_da_Ocorrência', 'Municipio', 'UF', 'Regiao', 'Descricao_do_Tipo',
       'ICAO', 'Latitude', 'Longitude', 'Tipo_de_Aerodromo', 'Historico',
       'Matricula', 'Categoria_da_Aeronave', 'Operador', 'Tipo_de_Ocorrencia',
       'Fase_da_Operacao', 'Operacao', 'Danos_a_Aeronave',
       'Aerodromo_de_Destino', 'Aerodromo_de_Origem',
       'Lesoes_Fatais_Tripulantes', 'Lesoes_Fatais_Passageiros',
       'Lesoes_Fatais_Terceiros', 'Lesoes_Graves_Tripulantes',
       'Lesoes_Graves_Passageiros', 'Lesoes_Graves_Terceiros',
       'Lesoes_Leves_Tripulantes', 'Lesoes_Leves_Passageiros',
       'Lesoes_Leves_Terceiros', 'Ilesos_Tripulantes', 'Ilesos_Passageiros',
       'Lesoes_Desconhecidas_Tripulantes', 'Lesoes_Desconhecidas_Passageiros',
       'Lesoes_Desconhecidas_Terceiros', 'Modelo', 'CLS', 'Tipo_ICAO', 'PMD',
       'Numero_de_Assentos', 'Nome_do_Fabricante', 'PSSO'],
      dtype='object')

In [3]:
colunas = ["Numero_da_Ocorrencia", "Classificacao_da_Ocorrência", "Data_da_Ocorrencia","Municipio","UF","Regiao","Nome_do_Fabricante"]
df = df[colunas]

In [4]:
df.rename( columns={  'Classificacao_da_Ocorrência' : 'Classificacao_da_Ocorrencia'  } ,inplace=True )

In [5]:
df.head(10)

,Numero_da_Ocorrencia,Classificacao_da_Ocorrencia,Data_da_Ocorrencia,Municipio,UF,Regiao,Nome_do_Fabricante
0,7762,Incidente,2018-03-21,SÃO PAULO,SP,Sudeste,AGUSTA
1,7759,Acidente,2018-03-14,MONTES CLAROS,MG,Sudeste,CESSNA AIRCRAFT
2,7758,Acidente,2018-01-26,INACIOLÂNDIA,GO,Centro-Oeste,CESSNA AIRCRAFT
3,7758,Acidente,2018-01-26,INACIOLÂNDIA,GO,Centro-Oeste,CESSNA AIRCRAFT
4,7757,Incidente Grave,2018-03-18,TORRES,RS,Sul,PIPER AIRCRAFT
5,5552,Acidente,2009-07-07,None,PR,Sul,None
6,5118,Acidente,2006-10-13,None,ES,Sudeste,PIPER AIRCRAFT
7,7756,Incidente Grave,2018-03-18,IGARASSÚ,PE,Nordeste,KAIO AMARAL RANGEL
8,7755,Incidente Grave,2018-03-18,MARAGOGI,AL,Nordeste,HENRIQUE DRUMOND LIMA DE OLIVEIRA
9,7754,Incidente Grave,2018-03-17,BRAGANÇA PAULISTA,SP,Sudeste,NEIVA

In [ ]:
import psycopg2

# Parâmetros de conexão
dbname   = 'python'
user     = 'postgres'
password = '1989'
host     = 'localhost'
port     = '5432' 

# Criar uma conexão
conexao = psycopg2.connect(dbname=dbname,
                        user=user,
                        password=password,
                        host=host,
                        port=port)


cursor = conexao.cursor()

#Delete base antes da carga
cursor.execute(  " delete from public.Anac  ")

#Carga de Dados
for indice,coluna_df in df.iterrows():
    cursor.execute( """   insert into Anac (     
                Numero_da_Ocorrencia, 
                Classificacao_da_Ocorrencia, 
                Data_da_Ocorrencia, 
                Municipio, 
                UF, 
                Regiao, 
                Nome_do_Fabricante
            ) VALUES (%s,%s,%s,%s,%s,%s,%s) 
                
            """ ,(
                coluna_df["Numero_da_Ocorrencia"],
                coluna_df["Classificacao_da_Ocorrencia"],
                coluna_df["Data_da_Ocorrencia"],
                coluna_df["Municipio"],
                coluna_df["UF"],
                coluna_df["Regiao"],
                coluna_df["Nome_do_Fabricante"]                            
                
            )                   
            
            
            )

conexao.commit() 
cursor.close()
conexao.close()